### ISSUE TITLE
Build issue (minor)

### ISSUE THREAD

**Issue by alexalkis** [adtools/sfdc#5]
Hello there,
On building https://github.com/bebbo/amigaos-cross-toolchain , I get a break on build on the tool sfdc. I classify it as minor cause it breaks two time and then it continues somehow.

Here is output from break 1:
DEBUG: enter directory ".build-m68k/build/sfdc"
DEBUG: execute "make -j1"
pod2man sfdc -o sfdc.1
sfdc around line 5562: Non-ASCII character seen before =encoding in 'still�have'. Assuming ISO8859-1
sfdc around line 5570: '=item' outside of any '=over'
sfdc around line 5598: Expected text after =item, not a bullet
sfdc around line 5604: Expected text after =item, not a bullet
sfdc around line 5608: Expected text after =item, not a bullet
sfdc around line 5614: Expected text after =item, not a bullet
sfdc around line 5621: Expected text after =item, not a bullet
sfdc around line 5626: Expected text after =item, not a bullet
sfdc around line 5635: Expected text after =item, not a bullet
sfdc around line 5640: Expected text after =item, not a bullet
sfdc around line 5645: Expected text after =item, not a bullet
sfdc around line 5649: Expected text after =item, not a bullet
sfdc around line 5653: Expected text after =item, not a bullet
sfdc around line 5657: Expected text after =item, not a bullet
sfdc around line 5662: Expected text after =item, not a bullet
sfdc around line 5570: =over without closing =back
POD document had syntax errors at /usr/bin/pod2man line 68.
Makefile:56: recipe for target 'sfdc.1' failed
make: *** [sfdc.1] Error 255

Here from break 2:

pod2text -c sfdc -o sfdc.txt
sfdc around line 5562: Non-ASCII character seen before =encoding in 'still�have'. Assuming ISO8859-1
sfdc around line 5570: '=item' outside of any '=over'
sfdc around line 5598: Expected text after =item, not a bullet
sfdc around line 5604: Expected text after =item, not a bullet
sfdc around line 5608: Expected text after =item, not a bullet
sfdc around line 5614: Expected text after =item, not a bullet
sfdc around line 5621: Expected text after =item, not a bullet
sfdc around line 5626: Expected text after =item, not a bullet
sfdc around line 5635: Expected text after =item, not a bullet
sfdc around line 5640: Expected text after =item, not a bullet
sfdc around line 5645: Expected text after =item, not a bullet
sfdc around line 5649: Expected text after =item, not a bullet
sfdc around line 5653: Expected text after =item, not a bullet
sfdc around line 5657: Expected text after =item, not a bullet
sfdc around line 5662: Expected text after =item, not a bullet
sfdc around line 5570: =over without closing =back
POD document had syntax errors at /usr/bin/pod2text line 81.
Makefile:59: recipe for target 'sfdc.txt' failed
make: *** [sfdc.txt] Error 255
ERROR: command "make -j1" failed with 2

**Comment by jens-maus** [comment]
https://github.com/bebbo/amigaos-cross-toolchain  is an unsupported fork of https://github.com/cahirwpz/amigaos-cross-toolchain. Please ask @bebbo to merge his changes to the original author of the cross-toolchain and ask him to remove his funny commit "@" prefixes first because they are non-standard and just obfuscate the changelog. Sorry, but I really don't want to support yet another cross-toolchain ATM and also don't want to support bebbo simply forking @cahirwpz without contributing changes back.

**Comment by alexalkis** [comment]
Ok, thanks.  I reported the issue, just in case it would help you make your tool a bit more robust.
As I said in the title, it's pretty minor for me. :)
